### ISSUE TITLE
 How should I handle confirmation pop-up dialog

### ISSUE THREAD

**Issue by sylvoslee** [kamildemocko/PySapScript#4]
May I ask another question? After I click 'Execute', after a while, there will be a confirmation pop-up dialog. How should I handle this? thank you

**Comment by kamildemocko** [comment]
Usually, when you execute transaction, the SAP gets locked -- and PySapScript is locked as well - it waits until the SAP reacts again. So when the popup appears, the program continues to run, so you can have a following press action in place to press any button on the popup (confirm or cancel usually)

**Comment by kamildemocko** [comment]
i hope that answered your question.
