### ISSUE TITLE
Can pss.launch_sap skip the system message dialog box?

### ISSUE THREAD

**Issue by sylvoslee** [kamildemocko/PySapScript#5]
![123](https://github.com/kamildemocko/PySapScript/assets/34852097/f2e2ece5-3e3b-42d2-9704-6842d3c5dff1)

**Comment by kamildemocko** [comment]
I also get this messages from time to time. 
The default SAP startup setting is set to try to log in2 times if error occurred.
For me, first time this shows up, the SAP is killed and second time this does not show again.
